In [1]:
import numpy as np

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [9]:
a = np.random.randint(12, 24, 12)
a

array([14, 13, 21, 13, 15, 16, 18, 20, 13, 21, 15, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [14]:
a1 = a.reshape(2,6)
a2 = a.reshape(6,2)
a3 = a.reshape(3,4)
a4 = a.reshape(4,3)
a5 = a.reshape(1,12)

print(f'a1: {a1}\na2: {a2}\na3: {a3}\na4: {a4}\na5: {a5}')

a1: [[14 13 21 13 15 16]
 [18 20 13 21 15 23]]
a2: [[14 13]
 [21 13]
 [15 16]
 [18 20]
 [13 21]
 [15 23]]
a3: [[14 13 21 13]
 [15 16 18 20]
 [13 21 15 23]]
a4: [[14 13 21]
 [13 15 16]
 [18 20 13]
 [21 15 23]]
a5: [[14 13 21 13 15 16 18 20 13 21 15 23]]


Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [17]:
a1 = a.reshape(-1,6)
a2 = a.reshape(-1,2)
a3 = a.reshape(3,-1)
a4 = a.reshape(4,-1)
a5 = a.reshape(1,-1)

print(f'a1: {a1}\na2: {a2}\na3: {a3}\na4: {a4}\na5: {a5}')

a1: [[14 13 21 13 15 16]
 [18 20 13 21 15 23]]
a2: [[14 13]
 [21 13]
 [15 16]
 [18 20]
 [13 21]
 [15 23]]
a3: [[14 13 21 13]
 [15 16 18 20]
 [13 21 15 23]]
a4: [[14 13 21]
 [13 15 16]
 [18 20 13]
 [21 15 23]]
a5: [[14 13 21 13 15 16 18 20 13 21 15 23]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

-- Нет

In [27]:
a.reshape(12,1).ndim

2

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [28]:
a = np.random.randn(3,4)
a

array([[ 1.14279208,  1.1126379 , -0.15600982,  0.86694343],
       [-0.05597089, -0.18068776,  0.31709093,  1.34539756],
       [-1.87891512,  1.04952649, -1.50169165,  2.18022859]])

In [32]:
b = a.flatten()
b

array([ 1.14279208,  1.1126379 , -0.15600982,  0.86694343, -0.05597089,
       -0.18068776,  0.31709093,  1.34539756, -1.87891512,  1.04952649,
       -1.50169165,  2.18022859])

In [33]:
b.ndim

1

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [43]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

-- Нет разницы между ними

In [45]:
b = np.arange(20,1,-2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [47]:
np.array_equal(a, b)

True

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [54]:
a = np.zeros((2,2))
b = np.ones((3,2))

v = np.vstack((a,b))

print(f'a:\n{a}\n\nb:\n{b}\n\nv:\n{v}\n\nv.size: {v.size}')

a:
[[0. 0.]
 [0. 0.]]

b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

v:
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

v.size: 10


Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [67]:
a = np.arange(12)
A = a.reshape(4,3)
At = A.transpose()
B = np.dot(A, At)

print(f'a:\n{a}\n\nA:\n{A}\n\nAt:\n{At}\n\nB:\n{B}')

a:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

A:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

At:
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [73]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [77]:
c = np.arange(16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [85]:
C = c.reshape((4,4))
D = B + C * 10

D_det = np.linalg.det(D)
D_rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)

print(f'C:\n{C}\n\nD:\n{D}\n\nD_det: {D_det}\nD_rank: {D_rank}\n\nD_inv:\n{D_inv}')

C:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

D:
[[  5  24  43  62]
 [ 54 100 146 192]
 [103 176 249 322]
 [152 252 352 452]]

D_det: -7.685903354004529e-25
D_rank: 2

D_inv:
[[ 1.10382344e+13  5.26315789e-02 -3.31147031e+13  2.20764688e+13]
 [-8.46264636e+13  9.38249922e+13  6.62294063e+13 -7.54279349e+13]
 [ 1.36138224e+14 -1.87649984e+14 -3.31147031e+13  8.46264636e+13]
 [-6.25499948e+13  9.38249922e+13  0.00000000e+00 -3.12749974e+13]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [94]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0

print(f'D_inv:\n{D_inv}\n\nB:\n{B}\n\nC:\n{C}')

np.where([D_inv == 1], B, C)

D_inv:
[[1. 1. 0. 1.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 0. 0.]]

B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

C:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[[  5,  14,   2,  32],
        [  4,  50,  86,   7],
        [ 23,   9,  10, 212],
        [ 12, 122,  14,  15]]])